#!/bin/sh

log "Setting KMC permissions"
chmod -R a+rx /var/local/kmc/armel/*
chmod -R a+rx /var/local/kmc/armhf/*
chmod 0664 /var/local/kmc/persistence/kmc.conf
chmod a+rx /var/local/kmc/persistence/persistence.sh
chmod a+rx /var/local/kmc/persistence/run_persistence.sh

log "Setting KMC gandalf permissions"
for gandalf_arch in armel armhf; do
    make_mutable "/var/local/kmc/${gandalf_arch}/bin/gandalf"
    chown root:root "/var/local/kmc/${gandalf_arch}/bin/gandalf"
    chmod a+rx "/var/local/kmc/${gandalf_arch}/bin/gandalf"
    chmod +s "/var/local/kmc/${gandalf_arch}/bin/gandalf"
    ln -sf "/var/local/kmc/armel/bin/gandalf" "/var/local/kmc/armel/bin/su"
    ln -sf "/var/local/kmc/armhf/bin/gandalf" "/var/local/kmc/armhf/bin/su"
    make_immutable "/var/local/kmc/${gandalf_arch}/bin/gandalf"
done


log "Establishing Gandalf links"
rm -rf "/var/local/kmc/lib"
rm -rf "/var/local/kmc/bin"
ln -sf "/var/local/kmc/${ARCH}/lib" "/var/local/kmc/lib"
ln -sf "/var/local/kmc/${ARCH}/bin" "/var/local/kmc/bin"
ln -sf "/var/local/kmc/bin/gandalf" "/var/local/mkk/gandalf"
make_mutable /var/local/mkk
ln -sf "/var/local/mkk/gandalf" "/var/local/mkk/su"
make_immutable /var/local/mkk
make_immutable /var/local/kmc

log "Installing libkh binaries"
mkdir -p "/mnt/us/libkh/bin"
rm -f /mnt/us/libkh/bin/fbink
cp -f "/var/local/mkk/${ARCH}/bin/fbink" "/mnt/us/libkh/bin/fbink" # Yeah we do copying bc userstore is funky
chmod a+rx "/mnt/us/libkh/bin/fbink"
# Since the links to these binaries are SOFT links, no additional copying/linking is required

log "Deleting old hotfix"
cat /var/local/kmc/sql/appreg_cleanup_hotfix.sql | sqlite3 /var/local/appreg.db
rm /mnt/us/documents/*.run_hotfix

log "Setting up sh_integration"
cat /var/local/kmc/sql/appreg_register_sh_integration.sql | sqlite3 /var/local/appreg.db

log "Setting up persistence"
cat /var/local/kmc/sql/appreg_register_persistence_runner.sql | sqlite3 /var/local/appreg.db

echo "Generated by monolithic jb.sh v$JB_VERSION" > /mnt/us/documents/manually_run_persistence.run_persistence