###
# Run our system patches on every boot juuuuust in case something gets borked
# This USED to be the bridge script - Update persistence can't be done via upstart so we handle it with appreg.db
###
description "run_patch"
start on mounted_userstore and display_ready and loaded_touch
stop on stopping filesystems

task
script
    logger "hello from run_patch.conf" # bridge command is weird here

    sh /var/local/kmc/system_patches/run_patch.sh
end script
