name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Meson
      continue-on-error: true
      run: |
          sudo apt update
          sudo apt install python3 python3-pip python3-setuptools python3-wheel ninja-build
          pip3 install meson
    - uses: actions/checkout@v4
      with:
        repository: KindleModding/kindle-sdk
        submodules: recursive
        path: kindle-sdk
    - name: Download Kindle toolchains
      run: |
            wget -q https://github.com/KindleModding/koxtoolchain/releases/latest/download/kindlepw2.tar.gz -O - | tar -xzf - -C ~
            wget -q https://github.com/KindleModding/koxtoolchain/releases/latest/download/kindlehf.tar.gz -O - | tar -xzf - -C ~
    - name: Setup kindle-sdk + dependencies
      run: |
          sudo apt install -y zlib1g-dev libarchive-dev nettle-dev aria2
          bash ./kindle-sdk/gen-sdk.sh kindlepw2
          bash ./kindle-sdk/gen-sdk.sh kindlehf
    - name: Build jb.sh
      run: |
            LOGGING=1 ./build.sh
    - uses: actions/upload-artifact@v4
      with:
        name: jb.sh
        path: build/jb.sh