name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - uses: ./.github/actions/build